site_name: Alejandra Arriola
nav:
  - General Information: index.md
  - Profile: 
    - Education and Experience: educationandexperience.md
    - Selected Past Work: 'pastwork.md'



theme:
  name: material
  logo: images/wizeline.png
  features:
    - header.autohide

extra_css:
  - css/extra.css
